Feature/consumer estacionamento
ICEI-PUC-Minas-PMV-ADS/estacionamentoeixo4-back-end pull request #2
Opened 2023-05-12 20:16 UTC by MerianeRDias

- Alteração da tabela Veículo 
- Criação da tabela Reserva no modelo prisma
- Alteração model Veículo
- Alterações da api consumer para configuração de rota para Avaliação

2023-05-13 19:11 UTC, Jhonata-Jackson requested changes

2023-05-13 19:11 UTC, Jhonata-Jackson commented on api_consumer/Migrations/20230510225046_adicionandoTabelaAvaliacao.cs
não versionar migration agora

2023-05-13 19:11 UTC, Jhonata-Jackson commented on api_producer/node_modules/.prisma/client/index-browser.js
não versionar node_modules

2023-05-13 20:56 UTC, juliosergionovaesgomes approved these changes

2023-05-13 21:25 UTC, merged

2023-05-19 04:14 UTC, juliosergionovaesgomes commented
@Jhonata-Jackson  da um confere e mergea a minha, cancela a sua